 gazebo_ros_control:
      pid_gains:
        front_left_steering_joint:
          p: 100
          i: 0.01
          d: 10
        front_right_steering_joint:
          p: 100
          i: 0.01
          d: 10
        rear_left_steering_joint:
          p: 100
          i: 0.01
          d: 10
        rear_right_steering_joint:
          p: 100
          i: 0.01
          d: 10
        front_left_wheel_joint: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        front_right_wheel_joint: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        rear_left_wheel_joint: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        rear_right_wheel_joint: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0